### ISSUE TITLE
osx_keychain set crashing.  "Can't store password in Keychain"

### ISSUE THREAD

**Issue by Mattimus333** [seattlerb/osx_keychain#4]
Hey I'm using a string of modules(cocoapods-keys) that are relying on OSX keychain and it's crashing when trying to set on line 10.  I'm having no luck figuring out what is causing this.  Worth a shot to see if anyone here can help me out.  Any ideas?  Thanks in advance!

RuntimeError - Can't store password in Keychain
/Users/Matt/.rvm/gems/ruby-2.4.1@global/gems/osx_keychain-1.0.2/lib/osx_keychain.rb:10:in `set'
/Users/Matt/.rvm/gems/ruby-2.4.1@global/gems/osx_keychain-1.0.2/lib/osx_keychain.rb:10:in `[]='
/Users/Matt/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-keys-2.0.2/lib/keyring.rb:34:in `save'
/Users/Matt/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-keys-2.0.2/lib/pod/command/keys/set.rb:45:in `run'

**Comment by AhmedAskar** [comment]
Do you reach to the solution ?
