### ISSUE TITLE
osx_keychain fails on M1 Macs

### ISSUE THREAD

**Issue by DreamingInBinary** [seattlerb/osx_keychain#5]
I noticed while attempting to use Cocoapod's `cocoapods-keys` plugin that it would fail with this error:

```
LoadError - dlopen(/Users/jordanmorgan/.ruby_inline/ruby-2.7.0/Inline_OSXKeychain_5b2f8d1cd1bde9c4ff3fea49f09cd5c1.bundle, 9): no suitable image found.  Did find:
	/Users/jordanmorgan/.ruby_inline/ruby-2.7.0/Inline_OSXKeychain_5b2f8d1cd1bde9c4ff3fea49f09cd5c1.bundle: mach-o, but wrong architecture
```

Which led me to try and use this library by itself, which does indeed crash out:

```
jordanmorgan@Jordans-MacBook-Air ~ % osx_keychain
Traceback (most recent call last):
	10: from /Users/jordanmorgan/.rbenv/versions/2.7.2/bin/osx_keychain:23:in `<main>'
	 9: from /Users/jordanmorgan/.rbenv/versions/2.7.2/bin/osx_keychain:23:in `load'
	 8: from /Users/jordanmorgan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/osx_keychain-1.0.2/bin/osx_keychain:3:in `<top (required)>'
	 7: from /Users/jordanmorgan/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 6: from /Users/jordanmorgan/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 5: from /Users/jordanmorgan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/osx_keychain-1.0.2/lib/osx_keychain.rb:6:in `<top (required)>'
	 4: from /Users/jordanmorgan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/osx_keychain-1.0.2/lib/osx_keychain.rb:16:in `<class:OSXKeychain>'
	 3: from /Users/jordanmorgan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/RubyInline-3.12.5/lib/inline.rb:860:in `inline'
	 2: from /Users/jordanmorgan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/RubyInline-3.12.5/lib/inline.rb:526:in `load'
	 1: from /Users/jordanmorgan/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Users/jordanmorgan/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': dlopen(/Users/jordanmorgan/.ruby_inline/ruby-2.7.0/Inline_OSXKeychain_5b2f8d1cd1bde9c4ff3fea49f09cd5c1.bundle, 9): no suitable image found.  Did find: (LoadError)
	/Users/jordanmorgan/.ruby_inline/ruby-2.7.0/Inline_OSXKeychain_5b2f8d1cd1bde9c4ff3fea49f09cd5c1.bundle: mach-o, but wrong architecture
	/Users/jordanmorgan/.ruby_inline/ruby-2.7.0/Inline_OSXKeychain_5b2f8d1cd1bde9c4ff3fea49f09cd5c1.bundle: mach-o, but wrong architecture - /Users/jordanmorgan/.ruby_inline/ruby-2.7.0/Inline_OSXKeychain_5b2f8d1cd1bde9c4ff3fea49f09cd5c1.bundle
```

It appears [that in line 23](https://github.com/seattlerb/osx_keychain/blob/master/lib/osx_keychain.rb?#L23), when loading up `CoreFoundation`, the error occurs.

I'm not sure if there is a fix for this or not, but if there's anything I can do to help - I'm happy to!

**Comment by zenspider** [comment]
That looks like you migrated the old binary for your old architecture to an M1 machine. It is understandable that it would blow up. Nuke your `.ruby_inline` directory and rerun and it should rebuild for you.

If you're using a stock ruby on the M1 tho... it'll blow up for different reasons (missing headers). Using rbenv and the like works fine.

**Comment by DreamingInBinary** [comment]
@zenspider you're right, I initially couldn't get `rbenv` to install another Ruby version. Going all the way back and installing Homebrew and friends using `arch -x86_64` fixed this and several other issues.

Closing this down, thanks for responding!

**Comment by zenspider** [comment]
I'm curious what went wrong trying to build native m1 rubies.

**Comment by DreamingInBinary** [comment]
For me, I was using Ruby 7.2.x. When I suspected I needed another version, my first hint that something was off was that `rbenv` would fail any installation of Ruby.

Reinstalling Homebrew and `rbenv`, and finally getting this version of Ruby:
`ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]`

Fixed my issue. `ffi`, among others, would fail with a similar error above.

**Comment by sawalon** [comment]
https://github.com/orta/cocoapods-keys/issues/217#issuecomment-1304420876
fixed my  issue.
